image: julia:latest

variables:
  CACHE_DIR: "$CI_PROJECT_DIR/julia_pkg"

cache: &juliacache
  key: "julia-cache"
  paths:
    - "$CACHE_DIR"

before_script:
    - export JULIA_DEPOT_PATH="$CACHE_DIR"
    - export JULIA_PROJECT="."

.script:
  script:
    - |
      julia --project=@. -e '
        using Pkg
        Pkg.build()
        Pkg.test(coverage=true)'
.coverage:
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - |
      julia -e '
        using Pkg
        Pkg.add("Coverage")
        using Coverage
        c, t = get_summary(process_folder())
        using Printf
        @printf "Test coverage %.2f%%\n" 100c / t'

test (julia latest):
  cache: *juliacache
  extends:
    - .script
    - .coverage

pages:
  cache: *juliacache
  stage: deploy
  script:
    - julia --project=@. -e 'using Pkg; Pkg.build();'
    - |
      julia --project=docs -e '
        using Pkg
        Pkg.develop(PackageSpec(path=pwd()))
        Pkg.instantiate()'
    - julia --project=@. --color=yes docs/make.jl
    - mkdir -p public
    - mv docs/build public
  artifacts:
    paths:
      - public
  only:
    - main
